# https://www.linkedin.com/learning/learning-github-actions-2/solution-develop-a-workflow-that-creates-an-artifact?autoSkip=true&resume=false&u=2154097
# chapter 3 

name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Show Repo Contents
        run: |
          pwd
          ls -l
          echo
          find . -type f -print
          echo
          # which perl
          # echo 
          
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
