name: CreatePackage
 
on:
  workflow_dispatch:
    inputs:
      tagName:
        required: true
        type: string  
  #    version:
  #      required: false
      
  # push:
    # branches: ['main']
      
env:
  ARTIFACTORY_REGISTRY: https://bpd01artifactory.glideportal.transurban.com.au/artifactory
  GITHUB_CONTEXT: ${{toJson(github)}}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  CreatePackage:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
      packages: write
 
    steps:
      - name: Setup Environment Variables
        run: |
          echo "app_name=$( echo ${{ github.repository }} | cut -f2 -d'/' | tr "[:lower:]" "[:upper:]" | sed 's/-/_/g' )" >> $GITHUB_ENV
          echo "branch_name=$( echo ${{ github.event.inputs.tagName }} | cut -f1 -d'-' )" >> $GITHUB_ENV
          echo "version_num=$( echo ${{ github.event.inputs.tagName }} | cut -f2 -d'-' )" >> $GITHUB_ENV
          echo "package_name=$( echo ${{ github.repository }} | cut -f2 -d'/' | tr "[:lower:]" "[:upper:]" | sed 's/-/_/g' )-${{ github.event.inputs.tagName }}" >> $GITHUB_ENV

      - name: Show Environment Variables
        run: |
          echo "app_name : ${{ env.app_name }}"
          echo "branch_name : ${{ env.branch_name }}"
          echo "version_num : ${{ env.version_num }}"
          echo "package_name : ${{ env.package_name }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          # Fetch all history for all tags and branches
          fetch-depth: 0 
          # Checkout a different branch
          ref: ${{ github.event.inputs.tagName }} 
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: ${{ env.package_name }}

      - name: Show Repo Contents
        run: |
          #git tag -l
          pwd
          ls -l
          echo
          find ${{ env.package_name }} -print
          echo
          which perl
          echo 

      - name: Prepage Artifactory package
        run: |
          zip -r ./${{ env.package_name }}.zip ./${{ env.package_name }} -x "./${{ env.package_name }}/.git*/" "./${{ env.package_name }}/opsjobs" @
          echo
          unzip -l ./${{ env.package_name }}.zip
          echo
          ls -l

      - name: UploadToArtifactory
        run: |
          echo "ArtifactoryURL : ${{ env.ARTIFACTORY_REGISTRY }}/${{ env.app_name }}/${{ env.branch_name }}/${{ env.version_num }}"


      # - name: PackageCreate
      #   id: PackageCreate
      #   env: 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.event.inputs.tagName }}
      #   run: |    
      #     PackageName="${GITHUB_REPOSITORY#*/}"
      #     PackageName="${PackageName^^}-${tag}"
      #     echo "branchName is : ${PackageName}"
      #     echo "test: ${PackageName}"
      #     gh release create "${PackageName}" \
      #       --repo="$GITHUB_REPOSITORY" \
      #       --title="${PackageName}" #\
      #     # --generate-notes

      # - name: createPackage
      #   id: createPackage
      #   env: 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #   run: | 
      #     ls -l
      #     pwd

      # - name: Zip directory
      #   run: |
      #     cd ${{ github.workspace }}
      #     zip -r output.zip .
      
      # - name: Upload zip
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-artifact
      #     path: ${{ github.workspace }}/output.zip
