name: CreateTag
 
on:
  workflow_dispatch:
    inputs:
      tagName:
        required: true
        type: string  
      version:
        required: false
      
  push:
    # branches: ['main']
      
env:
  ARTIFACTORY_REGISTRY: https://bpd01artifactory.glideportal.transurban.com.au/artifactory
  GITHUB_CONTEXT: ${{toJson(github)}}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  CreateTag:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
      packages: write
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: getBranchName
        id: getBranchName
        run: |   
          branchName=$(echo ${{github.ref_name}})
          echo "getBranchName=$branchName">> $GITHUB_OUTPUT


      - name: listTag
        # run: git describe --tags `git rev-list --tags --max-count=1`    
        run: git tag -l 

      - name: createTag
        id: createTag
        env: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |      
          echo "${{steps.getBranchName.outputs.getBranchName}}"
          #tags=$(git tag -l)
          #echo "$tags" 
          git tag -l >> /tmp/tmp.out
          cat /tmp/tmp.out | grep "^$" | wc -l 
          TagCount=$(cat /tmp/tmp.out | grep "${{steps.getBranchName.outputs.getBranchName}}" | wc -l)

          echo "TagCount ${TagCount}"

          if [ ${TagCount} -eq 0 ]
          then
             VersionNum=1
          else
             echo Nothing yet
          fi
          NewTag=${{steps.getBranchName.outputs.getBranchName}}"-"$( echo $VersionNum | awk '{ printf "%04s", $1 }' )
          echo "NewTag: ${NewTag}"
