name: Show.Environment
on:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu Check
    runs-on: ubuntu-latest
    steps:
      - name: Say Ubuntu
        run: echo Ubuntu

  windows:
    name: Windows Check
    runs-on: windows-latest
    steps:
      - name: Say Windows
        run: echo Windows

  macos:
    name: MacOS Check
    runs-on: macos-latest
    steps:
      - name: Say MacOS
        run: echo MacOS

  show_env:
    name: Show Environment Step
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Run Multi commands
        run: echo
      - run: echo "Hello Everyone!"
      - run: date
      - run: df -h
      - run: env

