name: Tag.Branch
on:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu Check
    runs-on: ubuntu-latest
    steps:
      - name: Say Ubuntu
        run: echo Ubuntu

#  windows:
#    name: Windows Check
#    runs-on: windows-latest
#    steps:
#      - name: Say Windows
#        run: echo Windows
#
#  macos:
#    name: MacOS Check
#    runs-on: macos-latest
#    steps:
#      - name: Say MacOS
#        run: echo MacOS

  tag_branch:
    name: Tag.
    needs: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name:  Git checkout
        run: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

